import argparse
import os
import mlflow
import torch
from sklearn.svm import SVC
import json
import numpy as np

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--tensors", type=str, required=True, help="Path to input tensors")
    parser.add_argument("--params", type=str, required=True, help="Path to Katib optimal params")
    parser.add_argument("--mlflow-uri", type=str, required=True, help="MLflow Tracking URI")
    args = parser.parse_args()

    mlflow.set_tracking_uri(args.mlflow_uri)

    print(f"Loading optimal parameters from {args.params}...")
    with open(args.params, "r") as f:
        params = json.load(f)
    print(f"Katib Sweep Params: {params}")

    print("Loading optimal ResNet from MLflow...")
    # In a real environment, you'd fetch the specific run that matched Katib's best trial.
    # For now, we'll load the latest registered model or dummy it.
    try:
        model = mlflow.pytorch.load_model("models:/resnet-bearid/latest")
        model.eval()
        device = torch.device("cpu")
        model.to(device)
    except Exception as e:
        print(f"Failed to load ResNet from MLflow: {e}. Using dummy embeddings for test.")
        model = None
    
    print(f"Generating 128D embeddings from tensors in {args.tensors}...")
    X_embeddings = []
    y_labels = []
    
    # Mock reading the .pt files generated by preprocess
    # In production: for file in os.listdir(args.tensors): data, label = torch.load(file)...
    dummy_data = torch.randn(10, 3, 224, 224)
    dummy_labels = np.random.randint(0, 3, 10)
    
    if model:
        with torch.no_grad():
            embeddings = model(dummy_data)
            X_embeddings = embeddings.numpy()
            y_labels = dummy_labels
    else:
        # Fallback to dummy
        X_embeddings = np.random.randn(10, 128)
        y_labels = dummy_labels

    print("Fitting sklearn SVM...")
    svm = SVC(kernel="linear", probability=True)
    svm.fit(X_embeddings, y_labels)
    
    acc = svm.score(X_embeddings, y_labels)
    print(f"SVM Training Accuracy: {acc:.4f}")

    with mlflow.start_run():
        print("Logging SVM to MLflow...")
        mlflow.sklearn.log_model(svm, "bearid-svm")
        
    print("SVM Fitting complete.")

if __name__ == "__main__":
    main()
